### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by boerni667** [OPENER-next/OpenStop#123]
### Idea

Please add this app to F-Droid for the truely paranoid open source enthusiasts among us. :)

### Implementation

https://f-droid.org/docs/FAQ_-_App_Developers/

### Additional Info

https://f-droid.org/docs/FAQ_-_App_Developers/

**Comment by Robbendebiene** [comment]
Thanks for your request!

Being such people our selves (at least partly 😀) we actually already tried bringing the app to the F-Droid store. There even existed a link in our GitHub repository readme to the anticipated store page: https://github.com/OPENER-next/OpenStop/issues/88
However due to policy conflicts caused by the geo-positioning library we use, we were not able to get OpenStop to F-Droid yet despite some efforts like submitting patches to the geo-positioning library.

Long story short: the geo-positioning library contains (unused) references to proprietary code (Google Location Services) which is against the F-Droid policy. Full discussion/history can be found in the dedicated [F-Droid Merge Request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991#note_938539763).

Since our time is limited we had to cancel the whole process at a certain point for now.

Related issues are:
- https://github.com/Baseflow/flutter-geolocator/issues/841
- https://github.com/Baseflow/flutter-geolocator/pull/1050

**Comment by mnalis** [comment]
(it seems the work has been happening recently on https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991 so one may remain hopeful)

**Comment by 7h30n3** [comment]
It's finally done. OpenStop can now be found on F-Droid: https://f-droid.org/packages/de.tu_chemnitz.etit.sse.openstop/
Anyone who wants to see what the torture was can do so here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991

**Comment by mnalis** [comment]
I can confirm it is available on f-droid and seems to work!

At least I _think_ it works, as I don't speak German unfortunately :cry: so I'm to scared to go much further than welcome screen (hoping for https://github.com/OPENER-next/OpenStop/issues/148 :heart_eyes:)

**Comment by 7h30n3** [comment]
Finally added F-Droid badge to README.md and to [openstop.app](https://openstop.app) (https://github.com/OPENER-next/OpenStop-website/commit/b1eaffd32374263a222e6f39126384c883b27386 )
