### ISSUE TITLE
Logging out (and logging in with a different account) is impossible

### ISSUE THREAD

**Issue by wielandb** [OPENER-next/OpenStop#129]
### Problem

Once you log into an OSM-account in OpenStop, it is impossible to log in with another account. Logging out and logging in again just results in your previous account automatically being authorized. (See attached video)

Even reinstalling the app does not solve this problem. 🫥

https://user-images.githubusercontent.com/29458682/210393547-9e15a4cb-d194-4fa7-b188-3a9150776603.mp4

### Which app version do you use?

0.3.0+8

### What operating system do you use?

Android

### What operating system *version* do you use?

10

**Comment by Robbendebiene** [comment]
The reason this happens is because you likely ticked the "remember me" box. For security reasons the login process is done entirely in your browser wherefore we have no control over the set cookies.

In theory we should be able to open an ephemeral session/incognito tab but it is currently only working on iOS: https://github.com/LinusU/flutter_web_auth/issues/144

As a workaround you should be able to clear the cache or logout of OSM in the browser that handles this process.

_________

OSM related issue: https://github.com/openstreetmap/openstreetmap-website/issues/3103
