### ISSUE TITLE
Add ability to show multiple images per answer

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OpenStop#140]
### Idea

Currently only the additional info to a question can show multiple images. It would be nice to have this ability with answers, too. So a variaty of scenarios or variants of certain objects can be shown to the user.
A little overlay indicator on the button can show the amount of images stored for a particular answer.

**Comment by Robbendebiene** [comment]
Cons:

- May act more as a workaround than a solution for the actual problem (the image is unrepresentative, the tag value is too vague)
- Depending on the case the better solution might be to add an additional answer which may write the same tag as another answer but is represented by different information (name, description, image). This is also less error prone because the user immediately recognizes it and doesn't have to check through "alternative images".
- Use illustrations instead of photos for a more generic representation and to dissuade the user from searching for a one to one replication of the object seen in the photo
