### ISSUE TITLE
Bus stops w/o "platform" do not show up in OpenStop

### ISSUE THREAD

**Issue by guerda** [OPENER-next/OpenStop#165]
### Problem

I have two bus stops, which do not show up in Open Stop. Usually, if all answers are given, the red circle still does show up. but not for this bus stop.

https://www.openstreetmap.org/node/4620120989
https://www.openstreetmap.org/node/5895952545

The nodes look like this:

```
<node id="4620120989" visible="true" version="5" changeset="66316196" timestamp="2019-01-14T22:12:25Z" user="FrankXF" uid="378954" lat="51.2405812" lon="6.7162284">
  <tag k="bus" v="yes"/>
  <tag k="highway" v="bus_stop"/>
  <tag k="local_ref" v="1"/>
  <tag k="name" v="Willstätterstraße"/>
  <tag k="public_transport" v="stop_position"/>
  <tag k="ref:IFOPT" v="de:05111:18177:1:1"/>
</node>
<node id="5895952545" visible="true" version="3" changeset="66316196" timestamp="2019-01-14T22:12:25Z" user="FrankXF" uid="378954" lat="51.2405922" lon="6.7162474">
  <tag k="bus" v="yes"/>
  <tag k="highway" v="bus_stop"/>
  <tag k="local_ref" v="2"/>
  <tag k="name" v="Willstätterstraße"/>
  <tag k="public_transport" v="stop_position"/>
  <tag k="ref:IFOPT" v="de:05111:18177:2:2"/>
</node>
```

They are also part of different relations for the bus lines etc.

Can you tell me why this doesn't show up?

### Which app version do you use?

0.4.1+11

### What operating system do you use?

Android

### What operating system *version* do you use?

13

**Comment by guerda** [comment]
It seems that `public_transport=platform` is missing. THis is why multiple bus stops don't appear on the app, even though it's only a recommendation, according to the wiki: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop (Important vs. required) and in the German version: https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dbus_stop ("recommended" instead of "required").

Is that intended?

**Comment by Robbendebiene** [comment]
Yes this is (or at least was) intended.
We decided to only include stops tagged via PTV2 mainly because the older schema has some uncertainties:
- sometimes a `highway=bus_stop` is mapped on the road (as the stop position)
- sometimes a separate node with `highway=bus_stop` is placed on a way with `highway=platform`/`public_transport=platform` (usually where the pole is)

Until recently we weren't able to detect/filter these cases.

I guess there is also a part of us which wants to push the PTV2 schema, because we consider it superior to PTV1 in various aspects (differentiation of tram and train stops, unified tagging, stop area relations, just to name a few of them).

Whether this decision supports the overall goal is certainly debatable.

**Comment by guerda** [comment]
Thank you for the explanation, I can understand it. It seems that some regions the old schema is still there. I will see where I can "upgrade" those without making a fuss with the local community. 

Thanks !
