### ISSUE TITLE
English translations updates?

### ISSUE THREAD

**Issue by mnalis** [OPENER-next/OpenStop#233]
### Idea

I see we now finally have translation tool available https://github.com/OPENER-next/OpenStop/issues/221, thanks!

However, I seem unable to change English translations on weblate site.

For example, key `parkingTypeMultiStoreyOption` has English text  `Parking garage`, while it would seem it is about  [parking=multi-storey](https://wiki.openstreetmap.org/wiki/Tag:parking=multi-storey), so something like `Multistorey car park` might be more fitting (as `parking=undergroud`, `parking=shed`, `amenity=garages` etc all might fit under _"Parking garage"_ umbrella).

---

So, what is the correct way to suggest updated English texts? Preferably in such way that Weblate will asks translators (who probably translated `Parking garage` to their language from English) to update their translations too?

**Comment by 7h30n3** [comment]
Hello @mnalis 
Changing a string of the reference language also often implies the change of the corresponding key, which isn't possible in Weblate, that's why I disabled it.
The correct way to suggest updated English texts is to create a PR. If the PR is approved and merged Weblate will automatically update their fork of OpenStop and asks users to re-translate / check that particular string.

**Comment by 7h30n3** [comment]
Fixed in bda0455.
