### ISSUE TITLE
If departures_board=realtime is set, why ask for passenger_information_display again?

### ISSUE THREAD

**Issue by schwindp** [OPENER-next/OpenStop#289]
### Problem

Given there's a platform where departures_board=realtime is already set - is there a valid reason to ask about availability of an Passenger Information Display? 
That already prefilled information could be used to skip towards the audio question

### Which app version do you use?

0.8.0+19

### What operating system do you use?

iOS

### What operating system *version* do you use?

17.6.1

**Comment by Robbendebiene** [comment]
The reason we initially didn't do this is because we considered `departures_board` to be a station wide display (showing departures from different platforms) and the `passenger_information_display` a platform wide display.
But certainly the community also uses it for simple platform wide displays, so I agree that we should treat `departures_board=realtime` on platforms to be equal to `passenger_information_display=yes`
